### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by mvksaran** [mikeebowen/node-wopi-server#9]
I have followed your instruction in read.me and had setup NodeJS 20.18 and was able to successfully launch the application. When I click AddExisting button and select a file, I see the below error. Wondering, if you could give me some tips on troubleshooting this issue

Error: read ECONNRESET
at TCP.OnStreaRead (node:internal/stream_base_commons:218.20
at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
errono: -4077,
code: 'ECONNRESET',
syscall: 'read'
}

**Comment by mvksaran** [comment]
I noticed this error only when running from VSCode. Running with npm start works fine.

**Comment by mikeebowen** [comment]
Interesting, I use VS Code and I haven't seen this error.

**Comment by mvksaran** [comment]
I spoke too soon. I get the error again in npm start as well. This time when I do Edit New, it happens. For Edit New, I give the filename that is already uploaded using Add Existing, right?  Add Existing worked well and copied the file to files folder. I gave the same file name and got this error. Tried few times with Edit New, still same error

**Comment by mikeebowen** [comment]
> For Edit New, I give the filename that is already uploaded using Add Existing, right?

No, for Edit New you should give a new unique file name

**Comment by mikeebowen** [comment]
@mvksaran, are you using Office Online Server or are you part of the CSPP?

**Comment by mvksaran** [comment]
using Office Online Server

**Comment by mikeebowen** [comment]
For OOS there is free official support from Microsoft. Send an email describing what's happening and include that you use OOS to <span>dochelp</span>@microsoft.com. And I can help more there. Full disclosure, I'm a member of that support team.

**Comment by mvksaran** [comment]
Thank you, will do. Appreciate all your help and quick response

Regards
Saran

**Comment by mikeebowen** [comment]
Closing this as we resolved the issue in a separate forum.
